using System;
using System.Collections.Generic;
using System.Linq;

/*
 *  Synopsis: Converts model errors to a list in order to be usable for AJAX forms.  (Page reloads
 *      use the model errors as is when generated by the Razor engine.)
 *  
 *  October 2016  Roland Wales
 *  
 *  Change log:
 */

namespace LUPC.Utilities
{
    public class ModelErrors
    {
        public class Error
        {
            public Error(string key, string message)
            {
                Key = key;
                Message = message;
            }

            public string Key { get; set; }
            public string Message { get; set; }
        }
        //public void toList(ModelStateDictionary ModelState, List<string> errors)
        //{
        //    /*
        //  * Capture model errors to send to the client and display to the user
        //  */
        //    var erroneousFields = ModelState.Where(ms => ms.Value.Errors.Any())
        //                                    .Select(x => new { x.Key, x.Value.Errors });

        //    foreach (var erroneousField in erroneousFields)
        //    {
        //        var fieldKey = erroneousField.Key;
        //        var fieldErrors = erroneousField.Errors
        //                           .Select(error => new Error(fieldKey, error.ErrorMessage));
        //        foreach (var error in fieldErrors)
        //        {
        //            errors.Add(error.Key + ": " + error.Message);
        //        }
        //    }
        //}
    }
}