//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Action_Number_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LU_Action_Number_Type()
        {
            this.Action = new HashSet<Action>();
        }
    
        public int LU_Action_Number_Type_ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> LU_Action_Category_ID { get; set; }
        public string YearIncluded { get; set; }
        public string COC_Type { get; set; }
        public string Display { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action { get; set; }
    }
}
