//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Fee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LU_Fee()
        {
            this.Check_Record = new HashSet<Check_Record>();
        }
    
        public int LU_Fee_ID { get; set; }
        public string Source_Code { get; set; }
        public string Description { get; set; }
        public string Fund { get; set; }
        public string Department { get; set; }
        public string Unit { get; set; }
        public string SubUnit { get; set; }
        public string Revenue { get; set; }
        public string LUPC_TP { get; set; }
        public string MRS_UT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check_Record> Check_Record { get; set; }
    }
}
