//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUPC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Action_Name> Action_Name { get; set; }
        public virtual DbSet<Action_Town> Action_Town { get; set; }
        public virtual DbSet<Check_Record> Check_Record { get; set; }
        public virtual DbSet<COC> COC { get; set; }
        public virtual DbSet<LU_Action_Number_Type> LU_Action_Number_Type { get; set; }
        public virtual DbSet<LU_Fee> LU_Fee { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Town> Town { get; set; }
    }
}
