//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Action_Name = new HashSet<Action_Name>();
        }
    
        public int Person_ID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public string Suffix { get; set; }
        public string Business_Name { get; set; }
        public Nullable<System.DateTime> Enter_Date { get; set; }
        public string Entered_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edited_By { get; set; }
        public byte[] timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Name> Action_Name { get; set; }
    }
}
