//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Town()
        {
            this.Action_Town = new HashSet<Action_Town>();
        }
    
        public int Town_ID { get; set; }
        public string Geocode { get; set; }
        public string Name { get; set; }
        public string Township_Range { get; set; }
        public string Alt_Name { get; set; }
        public Nullable<int> County_ID { get; set; }
        public string Type { get; set; }
        public string Zone_Map_Reference { get; set; }
        public string Active { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Town> Action_Town { get; set; }
    }
}
